# Generated by Django 4.2.13 on 2024-07-03 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_laptopgallery_laptop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='brand_name',
            new_name='brand',
        ),
    ]
