# Generated by Django 5.0.4 on 2024-06-24 17:38

from django.db import migrations


def set_price(apps, schema_editor):
    MULTIPLIER = 120

    smartphone_model = apps.get_model("main_app", "SmartPhone")
    models = smartphone_model.objects.all()
    for smartphone in models:
        smartphone.price = MULTIPLIER * len(smartphone.brand)
    smartphone_model.objects.bulk_update(models, ['price'])


def set_category(apps, schema_editor):
    smartphone_model = apps.get_model("main_app", "SmartPhone")
    models = smartphone_model.objects.all()
    for smartphone in models:
        if smartphone.price >= 750:
            smartphone.category = "Expensive"
        else:
            smartphone.category = "Cheap"

    smartphone_model.objects.bulk_update(models, ['category'])


def reverse_fulling_of_columns_category_and_price(apps, schema_editor):
    smartphone_model = apps.get_model("main_app", "SmartPhone")
    models = smartphone_model.objects.all()
    for smartphone in models:
        smartphone.category = smartphone_model._meta.get_field('category').default
        smartphone.price = smartphone_model._meta.get_field('price').default
    smartphone_model.objects.bulk_update(models, ['category'])
    smartphone_model.objects.bulk_update(models, ['price'])


def set_all_columns(apps, schema_editor):
    set_price(apps, schema_editor)
    set_category(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_smartphone'),
    ]

    operations = [
        migrations.RunPython(set_all_columns, reverse_fulling_of_columns_category_and_price)
    ]
