# Generated by Django 4.2.14 on 2024-07-29 11:08

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='author',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
